#!/bin/bash

#This script will allow port 80 and 8080, the third line will redirect port 80 to 8080

iptables -A INPUT -i eth0 -p tcp --dport 80 -j ACCEPT

iptables -A INPUT -i eth0 -p tcp --dport 8080 -j ACCEPT

iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT--to-port 8080



#!/bin/bash

#This will open the desired ports

firewall-cmd --zone=public --add-port=800/tcp --permanent

firewall-cmd --reload



#!/bin/bash

#This will allow ssh

iptables -A INPUT -i eth0 -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT



#!/bin/bash

#this will allow IMAP connections

iptables -A INPUT -i eth0 -p tcp --dport 143 -m state --state NEW,ESTABLISHED -j ACCEPT

iptables -A OUTPUT -o eth0 -p tcp --sport 143 -m state --state ESTABLISHED -j ACCEPT



#This will allow the pop3 connections

iptables -A INPUT -i eth0 -p tcp --dport 110 -m state --state NEW,ESTABLISHED -j ACCEPT

iptables -A OUTPUT -o eth0 -p tcp -sport 110 -m state --state ESTABLISHED -j ACCEPT



#!/bin/bash 

#this will allow you to block an user by IP

iptables -A INPUT -s 192.168.3.2 -j DROP



